sudo: false
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
cache:
  npm: true
  directories:
    - coverage
notifications:
  email: false
install: npm install && npm install -g codecov
script: npm run test:coverage && codecov
jobs:
  include:
    - stage: release
      if: branch = master AND type != pull_request
      node_js: '10'
      script: npm run semantic-release
